### ISSUE TITLE
Pipeline Mk2 throughput still capped at 600 m^3/min

### ISSUE THREAD

**Issue by Th3Fanbus** [kronflux/FasterBeltsAndMore_SMM#1]
I went to this spot in Blue Crater where there's two Pure Crude Oil nodes next to each other and set up a simple test: join the output of two Oil Extractors together and dump it into an Industrial Fluid Buffer using a single pipe. But the flow is still limited to 600 m^3/min, see attached screenshots.

I'm pretty sure this happens because of a known base game limitation, use the `>pipes600` command on FICSIT-Fred, a Discord bot in the [Satisfactory Modding Discord](https://discord.ficsit.app). Unfortunately, currently there's no good way to increase this limit.

![20240420082356_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/268bba74-9114-49ba-85fa-a24f74d2aeed)

![20240420082708_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/80c20bfd-4173-4177-aea4-b1ae5e450c75)

![20240420082714_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/933ecaf6-9610-4ba8-a898-a746770d7bde)

![20240420082341_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/cf564fe9-25e9-4563-894b-eeb0e2a7f6a9)

![20240420082617_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/5b80b31c-3cf4-4cd3-b626-6b89e5ef6a47)

![20240420082322_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/c0e5ad89-f25b-44a5-9fb0-8971ac988a8e)

![20240420082322_1](https://github.com/kronflux/FasterBeltsAndPipes_SMM/assets/22937129/562c6b71-4177-43cc-be40-c074f8545ce8)

**Comment by kronflux** [comment]
Yes, sadly you're correct, it seems to be a hard-coded limitation, I had removed the feature description from the mod listing, however I forgot to update it on the github description.
I left the changes in the mod, just in case anyone ever figures out how to get around it, this should then just simply "work" with whatever mod accomplishes this.

I will update the github readme to reflect the lack of this functionality.

Thanks for the feedback!

**Comment by Th3Fanbus** [comment]
> Yes, sadly you're correct, it seems to be a hard-coded limitation, I had removed the feature description from the mod listing, however I forgot to update it on the github description. I left the changes in the mod, just in case anyone ever figures out how to get around it, this should then just simply "work" with whatever mod accomplishes this.

It seems to be a limitation in how the fluid input/output ports work, so it's not easy to increase this limit without potentially breaking something about pipeline networks in the process. IIRC, Kyrium (a well-known modder) once made a mod that added true 1200/min pipes, but it had several issues and he eventually scrapped it.

Instead of trying to increase belt/pipe speeds, what other modders (including myself) have chosen to do is increase the "density" of parts (items/fluids). For example, https://ficsit.app/mod/Th3RecipeMod makes "compressed" parts that are worth 10x of the original part, and also makes recipes using those compressed parts. Yes, I know, the mod description is awful. I should at least add pictures to it.

> I will update the github readme to reflect the lack of this functionality.

Sounds good. I saw you also changed the mod reference to reflect this, which is not recommended as it can break people's saves (but in your case it's not that bad because your mod doesn't add new content).

> Thanks for the feedback!

You're welcome!
